services:
  fintree-scraper:
    image: fintree-scraper
    container_name: fintree-scraper
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    networks:
      - fintree-network

networks:
  fintree-scraper-network:
    name: fintree-scraper-network
