services:
  fintree-scraper:
    image: fintree-scraper
    container_name: fintree-scraper
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python main.py
    restart: always
    environment:
      - IN_CONTAINER=true
    volumes:
      - .:/app/
    ports:
      - 8080:8080
    networks:
      - fintree-network

networks:
  fintree-network:
    external: true
